version: "3"
services:
  node:
    build: .
    image: hi.com
    working_dir: /opt
    command: ["npm", "run", "dev"]
    volumes:
      - ./src:/opt/src
    ports:
      - 4000:9000
    container_name: dev.hi.com

networks:
  default:
    external:
      name: docker_default
