const MENU = [
  {
    name: 'Home',
    icon: 'el-icon-third-home',
    link: '',
    // selectable: false,
    // info: '',
  },
  {
    name: 'Hotels',
    icon: 'el-icon-third-hotel',
    link: '',
    // selectable: false,
    // info: '',
  },
  {
    name: 'Experiences',
    icon: 'el-icon-third-gongzuojingyan',
    link: '',
    // selectable: false,
    // info: '',
  },
  {
    name: 'Restaurants',
    icon: 'el-icon-third-restaurant',
    link: '',
    // selectable: false,
    // info: '',
  }, {
    name: 'Languages',
    icon: 'el-icon-third-language',
    link: '',
    // selectable: true,
    // info: '',
  },
  {
    name: 'Currencies',
    icon: 'el-icon-third-coins',
    link: '',
    // selectable: true,
    // info: '',
  }, {
    name: 'Deals',
    icon: 'el-icon-third-money-bill',
    link: '',
    // selectable: false,
    // info: '',
  },
  {
    name: 'Gallery',
    icon: 'el-icon-third-photo',
    link: '',
    // selectable: false,
    // info: '',
  }, {
    name: 'Manage Booking',
    icon: 'el-icon-third-pen',
    link: '',
    // selectable: false,
    // info: '',
  },
  {
    name: 'Support',
    icon: 'el-icon-third-support',
    link: '',
    // selectable: false,
    // info: '',
  }, {
    name: 'Contact Us',
    icon: 'el-icon-third-email',
    link: '',
    // selectable: false,
    // info: '',
  },
]
export default MENU
